language: node_js
node_js:
  - 'node'
dist: xenial
before_install:
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get update -qq
  - sudo apt-get install -y esl-erlang
  - sudo apt-get install -y elixir
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
